# Default values for tweetlator-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: us.gcr.io/translator-177201/tweetlator-api
  tag: 0.1.2
  pullPolicy: Always
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 8000
  logLevel: debug
ingress:
  enabled: true
  # Used to create an Ingress record.
  # hosts:
  #   - chart-example.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /translation
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
